-- ==============================================================================
-- SKEMA DATABASE SUPABASE - KELAS INDUSTRI PERTEMUAN 03
-- Project: Portofolio Goldie Gladwin (SMK RPL Kelas XI)
-- Jalankan query ini di Dashboard Supabase -> Menu "SQL Editor" -> Klik "Run"
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABEL UTAMA: proyek (Wajib - Pertemuan 03)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.proyek (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    judul TEXT NOT NULL,
    deskripsi TEXT NOT NULL,
    teknologi TEXT NOT NULL,
    link TEXT,
    kategori TEXT DEFAULT 'Web',
    image TEXT,
    role TEXT
);

-- Aktifkan Row Level Security (RLS) - Step 3 & 4
ALTER TABLE public.proyek ENABLE ROW LEVEL SECURITY;

-- Buat Policy SELECT Publik: Siapapun boleh membaca data proyek (Step 4)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.proyek;
CREATE POLICY "Enable read access for all users"
ON public.proyek
FOR SELECT
USING (true);

-- ------------------------------------------------------------------------------
-- 2. INSERT DATA AWAL KE TABEL proyek (Sesuai portofolio asli kamu di src/data.ts)
-- ------------------------------------------------------------------------------
INSERT INTO public.proyek (judul, deskripsi, teknologi, link, kategori, image, role)
VALUES
(
    'Student Management System',
    'A comprehensive school administration platform to record, manage, and evaluate student academic progress seamlessly.',
    'Next.js, Tailwind CSS, Shadcn UI, Supabase',
    'https://github.com/GoldieGladwin',
    'Web',
    '/images/managemens.png',
    'Full Stack Developer'
),
(
    'Internship Management System',
    'An integrated coordination platform connecting vocational students, faculty advisors, and industry partners (DUDI).',
    'Next.js, Tailwind CSS, Shadcn UI, Supabase',
    'https://github.com/GoldieGladwin',
    'Web',
    '/images/managementm.png',
    'System Architect & Developer'
),
(
    'Developer Workspace & Playground',
    'An interactive frontend experimentation platform built to test modern React architectures, custom hooks, and dynamic components.',
    'Next.js, Tailwind CSS, Shadcn UI',
    'https://github.com/GoldieGladwin',
    'Mobile',
    '/images/My app.png',
    'Frontend Engineer'
),
(
    'Game Account Rental Platform',
    'A feature-rich web portal for secure, automated game account rentals with an intuitive user interface and real-time management.',
    'Next.js, Tailwind CSS, Shadcn UI, Supabase',
    'https://github.com/GoldieGladwin',
    'IoT',
    '/images/pinjam.png',
    'Full Stack Developer'
);

