-- ==============================================================================
-- SKEMA LENGKAP SUPABASE - KELAS INDUSTRI PERTEMUAN 03 & 04
-- Project: Portofolio Goldie Gladwin (SMK RPL Kelas XI)
-- Keterangan:
-- 1. Tabel proyek + data awal + Policy SELECT publik
-- 2. Tabel profiles + Policy RLS role admin
-- 3. Policy CRUD (INSERT, UPDATE, DELETE) proyek HANYA untuk role admin
-- 4. Langsung otomatis membuat 1 Akun Admin (auth.users + profiles)
--
-- Cara Pakai:
-- Salin seluruh isi file ini, buka Dashboard Supabase -> SQL Editor -> Klik "Run"
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABEL UTAMA: proyek
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.proyek (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    judul TEXT NOT NULL,
    deskripsi TEXT NOT NULL,
    teknologi TEXT NOT NULL,
    link TEXT,
    link_deploy TEXT,
    kategori TEXT DEFAULT 'Web',
    image TEXT,
    role TEXT
);

-- Pastikan kolom link_deploy tersedia pada tabel proyek
ALTER TABLE public.proyek ADD COLUMN IF NOT EXISTS link_deploy TEXT;

-- Aktifkan Row Level Security (RLS) pada tabel proyek
ALTER TABLE public.proyek ENABLE ROW LEVEL SECURITY;

-- Policy SELECT Publik: Siapapun boleh membaca data proyek (Pertemuan 03)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.proyek;
CREATE POLICY "Enable read access for all users"
ON public.proyek
FOR SELECT
TO public
USING (true);

-- ------------------------------------------------------------------------------
-- 2. INSERT DATA AWAL KE TABEL proyek (Sesuai portofolio asli)
-- ------------------------------------------------------------------------------
INSERT INTO public.proyek (judul, deskripsi, teknologi, link, kategori, image, role)
VALUES
(
    'Student Management System',
    'A comprehensive school administration platform to record, manage, and evaluate student academic progress seamlessly.',
    'Next.js, Tailwind CSS, Shadcn UI, Supabase',
    'https://github.com/GoldieGladwin',
    'Web',
    '/images/managemens.png',
    'Full Stack Developer'
),
(
    'Internship Management System',
    'An integrated coordination platform connecting vocational students, faculty advisors, and industry partners (DUDI).',
    'Next.js, Tailwind CSS, Shadcn UI, Supabase',
    'https://github.com/GoldieGladwin',
    'Web',
    '/images/managementm.png',
    'System Architect & Developer'
),
(
    'Developer Workspace & Playground',
    'An interactive frontend experimentation platform built to test modern React architectures, custom hooks, and dynamic components.',
    'Next.js, Tailwind CSS, Shadcn UI',
    'https://github.com/GoldieGladwin',
    'Mobile',
    '/images/My app.png',
    'Frontend Engineer'
),
(
    'Game Account Rental Platform',
    'A feature-rich web portal for secure, automated game account rentals with an intuitive user interface and real-time management.',
    'Next.js, Tailwind CSS, Shadcn UI, Supabase',
    'https://github.com/GoldieGladwin',
    'IoT',
    '/images/pinjam.png',
    'Full Stack Developer'
)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------------------------
-- 3. TABEL PROFILES UNTUK VERIFIKASI ROLE ADMIN
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    role TEXT DEFAULT 'admin' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Aktifkan RLS pada tabel profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy SELECT: User yang login hanya boleh membaca profil miliknya sendiri
DROP POLICY IF EXISTS "Allow authenticated read own profile" ON public.profiles;
DROP POLICY IF EXISTS "Allow authenticated read profiles" ON public.profiles;
CREATE POLICY "Allow authenticated read own profile"
ON public.profiles
FOR SELECT
TO authenticated
USING (auth.uid() = id);

-- ------------------------------------------------------------------------------
-- 4. POLICIES CRUD TABEL PROYEK (HANYA UNTUK USER BER-ROLE 'admin' DI TABEL PROFILES)
-- ------------------------------------------------------------------------------

-- Policy 1: INSERT HANYA untuk user dengan role 'admin'
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.proyek;
DROP POLICY IF EXISTS "Allow admin insert" ON public.proyek;
CREATE POLICY "Allow admin insert"
ON public.proyek
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Policy 2: UPDATE HANYA untuk user dengan role 'admin'
DROP POLICY IF EXISTS "Allow authenticated update" ON public.proyek;
DROP POLICY IF EXISTS "Allow admin update" ON public.proyek;
CREATE POLICY "Allow admin update"
ON public.proyek
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Policy 3: DELETE HANYA untuk user dengan role 'admin'
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.proyek;
DROP POLICY IF EXISTS "Allow admin delete" ON public.proyek;
CREATE POLICY "Allow admin delete"
ON public.proyek
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- ------------------------------------------------------------------------------
-- 5. POLICIES CRUD TABEL PENGALAMAN (HANYA UNTUK USER BER-ROLE 'admin')
-- ------------------------------------------------------------------------------
ALTER TABLE public.pengalaman ENABLE ROW LEVEL SECURITY;

-- Policy SELECT Publik: Siapapun boleh membaca data pengalaman
DROP POLICY IF EXISTS "Enable read access for all users" ON public.pengalaman;
DROP POLICY IF EXISTS "Allow public read pengalaman" ON public.pengalaman;
CREATE POLICY "Allow public read pengalaman"
ON public.pengalaman
FOR SELECT
TO public
USING (true);

-- Policy INSERT: HANYA untuk user dengan role 'admin'
DROP POLICY IF EXISTS "Allow authenticated insert pengalaman" ON public.pengalaman;
DROP POLICY IF EXISTS "Allow admin insert pengalaman" ON public.pengalaman;
CREATE POLICY "Allow admin insert pengalaman"
ON public.pengalaman
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Policy UPDATE: HANYA untuk user dengan role 'admin'
DROP POLICY IF EXISTS "Allow authenticated update pengalaman" ON public.pengalaman;
DROP POLICY IF EXISTS "Allow admin update pengalaman" ON public.pengalaman;
CREATE POLICY "Allow admin update pengalaman"
ON public.pengalaman
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- Policy DELETE: HANYA untuk user dengan role 'admin'
DROP POLICY IF EXISTS "Allow authenticated delete pengalaman" ON public.pengalaman;
DROP POLICY IF EXISTS "Allow admin delete pengalaman" ON public.pengalaman;
CREATE POLICY "Allow admin delete pengalaman"
ON public.pengalaman
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- ------------------------------------------------------------------------------
-- 6. MEMBUAT 1 AKUN ADMIN OTOMATIS (AUTH.USERS + AUTH.IDENTITIES + PROFILES)
-- ------------------------------------------------------------------------------
-- Kredensial Akun Admin:
-- Email    : admin@gmail.com
-- Password : AdminPassword123!
-- ------------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$
DECLARE
  v_user_id UUID := gen_random_uuid();
  v_email TEXT := 'admin@gmail.com';
  v_password TEXT := 'AdminPassword123!';
BEGIN
  -- Cek jika akun belum ada di auth.users
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = v_email) THEN
    -- 1. Insert ke auth.users
    INSERT INTO auth.users (
      id,
      instance_id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at
    ) VALUES (
      v_user_id,
      '00000000-0000-0000-0000-000000000000',
      'authenticated',
      'authenticated',
      v_email,
      crypt(v_password, gen_salt('bf')),
      NOW(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{}'::jsonb,
      NOW(),
      NOW()
    );

    -- 2. Hubungkan identitas email ke auth.identities (wajib untuk GoTrue Supabase Auth)
    INSERT INTO auth.identities (
      id,
      user_id,
      provider_id,
      identity_data,
      provider,
      last_sign_in_at,
      created_at,
      updated_at
    ) VALUES (
      v_user_id,
      v_user_id,
      v_user_id,
      jsonb_build_object('sub', v_user_id, 'email', v_email),
      'email',
      NOW(),
      NOW(),
      NOW()
    );

    -- 3. Masukkan ke public.profiles dengan role 'admin'
    INSERT INTO public.profiles (id, email, role)
    VALUES (v_user_id, v_email, 'admin')
    ON CONFLICT (id) DO UPDATE SET role = 'admin';

  ELSE
    -- Jika user dengan email tersebut sudah pernah dibuat di auth.users:
    -- Ambil ID user lama dan pastikan terdaftar di tabel public.profiles sebagai admin
    SELECT id INTO v_user_id FROM auth.users WHERE email = v_email;
    
    -- Update password akun yang sudah ada ke AdminPassword123!
    UPDATE auth.users
    SET encrypted_password = crypt(v_password, gen_salt('bf')),
        email_confirmed_at = COALESCE(email_confirmed_at, NOW())
    WHERE id = v_user_id;

    INSERT INTO public.profiles (id, email, role)
    VALUES (v_user_id, v_email, 'admin')
    ON CONFLICT (id) DO UPDATE SET role = 'admin';
  END IF;
END $$;
